/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects.index'
import { Route as ProjectsNewRouteImport } from './routes/projects.new'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects.$projectId'
import { Route as ProjectsProjectIdIndexRouteImport } from './routes/projects.$projectId.index'
import { Route as ProjectsProjectIdDesignRouteImport } from './routes/projects.$projectId.design'
import { Route as ProjectsProjectIdDesignsDesignIdRouteImport } from './routes/projects.$projectId.designs.$designId'
import { Route as ProjectsProjectIdDesignsDesignIdIndexRouteImport } from './routes/projects.$projectId.designs.$designId.index'
import { Route as ProjectsProjectIdDesignsDesignIdFlowRouteImport } from './routes/projects.$projectId.designs.$designId.flow'

const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectsRoute,
} as any)
const ProjectsNewRoute = ProjectsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ProjectsRoute,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/$projectId',
  path: '/$projectId',
  getParentRoute: () => ProjectsRoute,
} as any)
const ProjectsProjectIdIndexRoute = ProjectsProjectIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectsProjectIdRoute,
} as any)
const ProjectsProjectIdDesignRoute = ProjectsProjectIdDesignRouteImport.update({
  id: '/design',
  path: '/design',
  getParentRoute: () => ProjectsProjectIdRoute,
} as any)
const ProjectsProjectIdDesignsDesignIdRoute =
  ProjectsProjectIdDesignsDesignIdRouteImport.update({
    id: '/designs/$designId',
    path: '/designs/$designId',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdDesignsDesignIdIndexRoute =
  ProjectsProjectIdDesignsDesignIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProjectsProjectIdDesignsDesignIdRoute,
  } as any)
const ProjectsProjectIdDesignsDesignIdFlowRoute =
  ProjectsProjectIdDesignsDesignIdFlowRouteImport.update({
    id: '/flow',
    path: '/flow',
    getParentRoute: () => ProjectsProjectIdDesignsDesignIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/projects/$projectId': typeof ProjectsProjectIdRouteWithChildren
  '/projects/new': typeof ProjectsNewRoute
  '/projects/': typeof ProjectsIndexRoute
  '/projects/$projectId/design': typeof ProjectsProjectIdDesignRoute
  '/projects/$projectId/': typeof ProjectsProjectIdIndexRoute
  '/projects/$projectId/designs/$designId': typeof ProjectsProjectIdDesignsDesignIdRouteWithChildren
  '/projects/$projectId/designs/$designId/flow': typeof ProjectsProjectIdDesignsDesignIdFlowRoute
  '/projects/$projectId/designs/$designId/': typeof ProjectsProjectIdDesignsDesignIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/projects/new': typeof ProjectsNewRoute
  '/projects': typeof ProjectsIndexRoute
  '/projects/$projectId/design': typeof ProjectsProjectIdDesignRoute
  '/projects/$projectId': typeof ProjectsProjectIdIndexRoute
  '/projects/$projectId/designs/$designId/flow': typeof ProjectsProjectIdDesignsDesignIdFlowRoute
  '/projects/$projectId/designs/$designId': typeof ProjectsProjectIdDesignsDesignIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/projects/$projectId': typeof ProjectsProjectIdRouteWithChildren
  '/projects/new': typeof ProjectsNewRoute
  '/projects/': typeof ProjectsIndexRoute
  '/projects/$projectId/design': typeof ProjectsProjectIdDesignRoute
  '/projects/$projectId/': typeof ProjectsProjectIdIndexRoute
  '/projects/$projectId/designs/$designId': typeof ProjectsProjectIdDesignsDesignIdRouteWithChildren
  '/projects/$projectId/designs/$designId/flow': typeof ProjectsProjectIdDesignsDesignIdFlowRoute
  '/projects/$projectId/designs/$designId/': typeof ProjectsProjectIdDesignsDesignIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/projects'
    | '/projects/$projectId'
    | '/projects/new'
    | '/projects/'
    | '/projects/$projectId/design'
    | '/projects/$projectId/'
    | '/projects/$projectId/designs/$designId'
    | '/projects/$projectId/designs/$designId/flow'
    | '/projects/$projectId/designs/$designId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/projects/new'
    | '/projects'
    | '/projects/$projectId/design'
    | '/projects/$projectId'
    | '/projects/$projectId/designs/$designId/flow'
    | '/projects/$projectId/designs/$designId'
  id:
    | '__root__'
    | '/'
    | '/projects'
    | '/projects/$projectId'
    | '/projects/new'
    | '/projects/'
    | '/projects/$projectId/design'
    | '/projects/$projectId/'
    | '/projects/$projectId/designs/$designId'
    | '/projects/$projectId/designs/$designId/flow'
    | '/projects/$projectId/designs/$designId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProjectsRoute: typeof ProjectsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/projects/new': {
      id: '/projects/new'
      path: '/new'
      fullPath: '/projects/new'
      preLoaderRoute: typeof ProjectsNewRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/projects/$projectId/': {
      id: '/projects/$projectId/'
      path: '/'
      fullPath: '/projects/$projectId/'
      preLoaderRoute: typeof ProjectsProjectIdIndexRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/design': {
      id: '/projects/$projectId/design'
      path: '/design'
      fullPath: '/projects/$projectId/design'
      preLoaderRoute: typeof ProjectsProjectIdDesignRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/designs/$designId': {
      id: '/projects/$projectId/designs/$designId'
      path: '/designs/$designId'
      fullPath: '/projects/$projectId/designs/$designId'
      preLoaderRoute: typeof ProjectsProjectIdDesignsDesignIdRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/designs/$designId/': {
      id: '/projects/$projectId/designs/$designId/'
      path: '/'
      fullPath: '/projects/$projectId/designs/$designId/'
      preLoaderRoute: typeof ProjectsProjectIdDesignsDesignIdIndexRouteImport
      parentRoute: typeof ProjectsProjectIdDesignsDesignIdRoute
    }
    '/projects/$projectId/designs/$designId/flow': {
      id: '/projects/$projectId/designs/$designId/flow'
      path: '/flow'
      fullPath: '/projects/$projectId/designs/$designId/flow'
      preLoaderRoute: typeof ProjectsProjectIdDesignsDesignIdFlowRouteImport
      parentRoute: typeof ProjectsProjectIdDesignsDesignIdRoute
    }
  }
}

interface ProjectsProjectIdDesignsDesignIdRouteChildren {
  ProjectsProjectIdDesignsDesignIdFlowRoute: typeof ProjectsProjectIdDesignsDesignIdFlowRoute
  ProjectsProjectIdDesignsDesignIdIndexRoute: typeof ProjectsProjectIdDesignsDesignIdIndexRoute
}

const ProjectsProjectIdDesignsDesignIdRouteChildren: ProjectsProjectIdDesignsDesignIdRouteChildren =
  {
    ProjectsProjectIdDesignsDesignIdFlowRoute:
      ProjectsProjectIdDesignsDesignIdFlowRoute,
    ProjectsProjectIdDesignsDesignIdIndexRoute:
      ProjectsProjectIdDesignsDesignIdIndexRoute,
  }

const ProjectsProjectIdDesignsDesignIdRouteWithChildren =
  ProjectsProjectIdDesignsDesignIdRoute._addFileChildren(
    ProjectsProjectIdDesignsDesignIdRouteChildren,
  )

interface ProjectsProjectIdRouteChildren {
  ProjectsProjectIdDesignRoute: typeof ProjectsProjectIdDesignRoute
  ProjectsProjectIdIndexRoute: typeof ProjectsProjectIdIndexRoute
  ProjectsProjectIdDesignsDesignIdRoute: typeof ProjectsProjectIdDesignsDesignIdRouteWithChildren
}

const ProjectsProjectIdRouteChildren: ProjectsProjectIdRouteChildren = {
  ProjectsProjectIdDesignRoute: ProjectsProjectIdDesignRoute,
  ProjectsProjectIdIndexRoute: ProjectsProjectIdIndexRoute,
  ProjectsProjectIdDesignsDesignIdRoute:
    ProjectsProjectIdDesignsDesignIdRouteWithChildren,
}

const ProjectsProjectIdRouteWithChildren =
  ProjectsProjectIdRoute._addFileChildren(ProjectsProjectIdRouteChildren)

interface ProjectsRouteChildren {
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRouteWithChildren
  ProjectsNewRoute: typeof ProjectsNewRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsProjectIdRoute: ProjectsProjectIdRouteWithChildren,
  ProjectsNewRoute: ProjectsNewRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProjectsRoute: ProjectsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
